Clean up and simplify build system customizations
* configure.ac (PATCH): Properly quote the AS_IF() macro arguments.
(GSTREAMERMM_MODULES): Use m4_foreach() to reduce repetition.
(ENABLE_GUI_EXAMPLES): Define an Automake conditional for the purpose
of excluding the GUI example programs from the build if gtkmm is not
available.  Remove the --enable-examples configure option, and always
build the GUI examples if gtkmm is available at build time.
(AC_CONFIG_FILES): Generate examples/Makefile unconditionally.
Remove tools/generate_gst_wrap_init.pl from the list of output files.
(GSTREAMERMM_WXXFLAGS): Remove -pedantic flag since it is too strict
for the gstreamer header files.
(GTHREAD_CFLAGS): Remove substitution variable for the thread-safety
compiler flags, as gstreamer itself depends on gthread and therefore
already includes the necessary flags in the pkg-config output.
(MM_ARG_WITH_TAGFILE_DOC): Remove reference to giomm-2.4.tag, which
does not exist.  Add tag file references for cairomm and pangomm.
Tentatively remove gtkmm-2.4.tag reference because gtkmm symbols are
not actually used in the documentation.  The mere presence of the
gtkmm tags already confuses Doxygen, causing it to link to gtkmm for
symbols in the Gst namespace.
* Makefile.am (DISTCHECK_CONFIGURE_FLAGS): As a temporary workaround,
disable fatal warnings during distcheck.
(SUBDIRS): Always recurse into tools/ and examples/.
* examples/Makefile.am (noinst_PROGRAMS): Make the inclusion of the
GUI examples depend on the ENABLE_GUI_EXAMPLES Automake conditional.
(AM_CPPFLAGS): Expand $(GUI_EXAMPLES_CFLAGS) if the GUI examples are
enabled, or $(GSTREAMERMM_CFLAGS) if not.
(LDADD): Link with $(GSTREAMERMM_LIBS) by default, and override the
global LDADD for the GUI programs to use $(GUI_EXAMPLES_LIBS).
* gstreamer/gstreamermm/Makefile.am: Completely kill the build rules
for patching the generated source code on the fly.  The single source
file this was applied to turns out to be fixable by other means.
* gstreamer/src/Makefile.am: Significantly simplify the convoluted
logic of the custom rules and expressions for generating the gmmproc
input files for the gstreamer plugins.
($(binding_outputdir)/gst_wrap_init.cc): Build gst_wrap_init.cc from
the src/ subdirectory like the other generated source files.
* gstreamer/src/element.ccg
(Gst::ElementInterfaced_WeakNotify_gstreamermm_callback): Remove
unused parameter name to avoid a compiler warning.
* gstreamer/src/filelist.am (files_hg): Combine variable assignments.
* gstreamer/src/taglist.hg (Gst::TagList): Call the special gmmproc
macro _CUSTOM_STRUCT_PROTOTYPE to suppress the output of a typedef
for the C struct.  This removes the need to patch the generated file.
* gstreamer/gstreamermm/taglist.h.patch: Delete obsolete file.
* tests/Makefile.am: Do not hard-code the libgstreamermm API version.
(AM_CXXFLAGS): Build tests with $(GSTREAMERMM_WXXFLAGS), too.
* tools/Makefile.am: Clean up and simplify.
* tools/extra_defs_gen/generate_plugin_gmmproc_file.cc: Add missing
struct initializers to avoid a compiler warning.
* tools/generate_gst_wrap_init.pl: Rename the configure input file
generate_gst_wrap_init.pl.in to generate_gst_wrap_init.pl.  Remove
the unnecessary she-bang line with the @PERL@ substitution, so that
it is no longer necessary for this file to be generated.

diff --git a/gstreamer/src/Makefile.am b/gstreamer/src/Makefile.am
--- a/gstreamer/src/Makefile.am
+++ b/gstreamer/src/Makefile.am
@@ -1,4 +1,4 @@
-# Copyright 2009 The gstreamermm Development Team
+## Copyright 2009 The gstreamermm Development Team
 ##
 ## This library is free software: you can redistribute it and/or modify it
 ## under the terms of the GNU Lesser General Public License as published
@@ -13,67 +13,53 @@
 ## You should have received a copy of the GNU Lesser General Public License
 ## along with this program.  If not, see <http://www.gnu.org/licenses/>.
 
-binding_name     = gstreamermm
-wrap_init_flags  = --namespace=Gst --parent_dir=gstreamermm
-codegen_srcdir   = $(top_srcdir)/tools
-extradefs_srcdir = $(codegen_srcdir)/extra_defs_gen
-m4_srcdir  	 = $(codegen_srcdir)/m4
-
-# The generate_plugin_gmmproc_file utility
-generate_plugin_gmmproc_file_source = $(extradefs_srcdir)/generate_plugin_gmmproc_file.cc
-generate_plugin_gmmproc_file_path = $(extradefs_srcdir)/generate_plugin_gmmproc_file
-generate_plugin_gmmproc_file_args = --namespace=Gst --main-defs=gst --target=gstreamermm
-run_generate_plugin_gmmproc_file = $(generate_plugin_gmmproc_file_path) $(generate_plugin_gmmproc_file_args)
+binding_name    = gstreamermm
+wrap_init_flags = --namespace=Gst --parent_dir=gstreamermm
+codegen_srcdir  = $(top_srcdir)/tools
 
 include $(srcdir)/filelist.am
 include $(top_srcdir)/tools/m4/filelist.am
 include $(top_srcdir)/build/generate-binding.am
 
-if MAINTAINER_MODE
-generate_plugin_dep = $(generate_plugin_gmmproc_file_source)
-endif
+other_built_sources  += $(binding_outputdir)/gst_wrap_init.cc
+MAINTAINERCLEANFILES += $(addprefix $(srcdir)/,$(plugins_ccg) $(plugins_hg))
 
-# The source file from which the license header may be extracted and placed in
-# plug-in generated .hg and .ccg files (use a file that probably will not
-# change because it will be a plug-in generation dependency):
-license_header_source_file = $(srcdir)/../gstreamermm/version.h
+generate_plugin_gmmproc_file = \
+	$(top_builddir)/tools/extra_defs_gen/generate_plugin_gmmproc_file$(EXEEXT) \
+	--namespace=Gst --main-defs=gst --target=gstreamermm
+generate_plugin_dependencies = \
+	$(codegen_srcdir)/extra_defs_gen/generate_plugin_gmmproc_file.cc \
+	$(addprefix $(codegen_m4_srcdir)/,$(files_plugin_m4))
+
+generate_gst_wrap_init = $(top_srcdir)/tools/generate_gst_wrap_init.pl
+
+target_plugin     = $(patsubst %element,%,$(basename $(notdir $@)))
+target_plugin_def = $(subst =, ,$(filter $(target_plugin)=%,$(GSTREAMERMM_PLUGIN_DEFS)))
+
+$(binding_outputdir)/gst_wrap_init.cc: $(generate_gst_wrap_init) $(binding_relfiles_hg)
+	$(AM_V_GEN)$(PERL) -- $(generate_gst_wrap_init) $(wrap_init_flags) \
+	 $(binding_relfiles_hg) >$@
 
 # This is to generate plugin .ccg files.  The generated .ccg file is piped
 # through m4 using the macros in tools/m4/ctocpp_base.m4 which then produces
 # the final .ccg file.
-$(plugins_ccg): $(generate_plugin_dep) $(files_plugin_m4:%=$(m4_srcdir)/%) \
-	$(license_header_source_file)
-	$(eval list_delim = $$(patsubst $$@,+,$$(plugins_ccg)))
-	$(eval prev_mems = $$(shell echo "$$(list_delim)" | cut -d'+' -f 1))
-	$(eval pos = $$(shell expr `echo "$$(prev_mems)" | wc -w` + 1))
-	$(eval plugin_def = $$(word $$(pos),$$(GSTREAMERMM_PLUGIN_DEFS)))
-	$(eval plugin_name = $$(shell echo "$$(plugin_def)" | cut -d'=' -f 1))
-	$(eval cppname = $$(subst $$(plugin_name)=,,$$(plugin_def)))
-if MAINTAINER_MODE
-	@if $(run_generate_plugin_gmmproc_file) --confirm-existence \
-		$(plugin_name); then true; else \
-		echo "The $(plugin_name) gstreamer plugin is not installed.  Aborting build. If you built gst-plugins-base from source code then you might need to install the appropriate -dev or --devel packages or enable experimenal plugins before rebuilding gst-plugins-base."; \
-		false; \
-	fi
-endif
-	$(AM_V_at)$(SED) -n '1,/^$$/p' $(license_header_source_file) > \
-		$(srcdir)/$@
-	$(AM_V_GEN)$(run_generate_plugin_gmmproc_file) --ccg $(plugin_name) \
-		$(cppname) | $(M4) -I $(m4_srcdir) >> $(srcdir)/$@
+# TODO: The confirm-existence check should probably run at configure time.
+# Also, even if this stays in the makefile, why the need for a separate
+# invocation of generate_plugin_gmmproc_file, when it could be done with
+# just one step?
+$(addprefix $(srcdir)/,$(plugins_ccg)): $(generate_plugin_dependencies)
+	@plugin='$(firstword $(target_plugin_def))'; \
+	 $(generate_plugin_gmmproc_file) --confirm-existence "$$plugin" || \
+	 (echo "The $$plugin gstreamer plugin is not installed. Aborting build."; \
+	  echo 'If you built gst-plugins-base from source code then you might need to'; \
+	  echo 'install the appropriate -dev or -devel packages or enable experimental'; \
+	  echo 'plugins before rebuilding gst-plugins-base.'; exit 1) >&2
+	$(AM_V_GEN)$(generate_plugin_gmmproc_file) --ccg $(target_plugin_def) \
+	 | $(M4) -I $(codegen_m4_srcdir) >$@
 
 # This is to generate plugin .hg files.  The generated .hg file is piped
 # through m4 using the macros in tools/m4/ctocpp_base.m4 which then produces
 # the final .hg file.
-$(plugins_hg): %.hg: $(generate_plugin_dep) \
-	$(files_plugin_m4:%=$(m4_srcdir)/%) $(license_header_source_file) %.ccg
-	$(eval list_delim = $$(patsubst $$@,+,$$(plugins_hg)))
-	$(eval prev_mems = $$(shell echo "$$(list_delim)" | cut -d'+' -f 1))
-	$(eval pos = $$(shell expr `echo "$$(prev_mems)" | wc -w` + 1))
-	$(eval plugin_def = $$(word $$(pos),$$(GSTREAMERMM_PLUGIN_DEFS)))
-	$(eval plugin_name = $$(shell echo "$$(plugin_def)" | cut -d'=' -f 1))
-	$(eval cppname = $$(subst $$(plugin_name)=,,$$(plugin_def)))
-	$(AM_V_at)$(SED) -n '1,/^$$/p' $(license_header_source_file) > $(srcdir)/$@
-	$(AM_V_GEN)$(run_generate_plugin_gmmproc_file) --hg $(plugin_name) \
-		$(cppname) | $(M4) -I $(m4_srcdir) >> $(srcdir)/$@
-
-MAINTAINERCLEANFILES += $(plugins_hg) $(plugins_ccg)
+$(addprefix $(srcdir)/,$(plugins_hg)): %.hg: %.ccg $(generate_plugin_dependencies)
+	$(AM_V_GEN)$(generate_plugin_gmmproc_file) --hg $(target_plugin_def) \
+	 | $(M4) -I $(codegen_m4_srcdir) >$@
